"use client";

import { Amplify } from "aws-amplify";

let configured = false;

/**
 * Lazily configure Amplify on first use.
 * Filters OAuth redirect URIs to match the current origin,
 * preventing Cognito redirect mismatches in multi-environment deployments.
 *
 * Must be called before any Amplify Auth operation.
 * Safe to call multiple times — only configures once.
 */
export function ensureAmplifyConfigured() {
  if (configured) return;
  if (typeof window === "undefined") return; // SSR guard

  try {
    // amplify_outputs.json is generated by `npx ampx sandbox` or `npx ampx pipeline-deploy`
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const outputs = require("../../amplify_outputs.json");
    const finalOutputs = JSON.parse(JSON.stringify(outputs));

    // Filter OAuth redirect URIs to match the current origin
    if (finalOutputs.auth?.oauth) {
      const currentOrigin = window.location.origin;

      if (Array.isArray(finalOutputs.auth.oauth.redirect_sign_in_uri)) {
        const match = finalOutputs.auth.oauth.redirect_sign_in_uri.find(
          (uri: string) => uri.startsWith(currentOrigin)
        );
        if (match) {
          finalOutputs.auth.oauth.redirect_sign_in_uri = [match];
        }
      }

      if (Array.isArray(finalOutputs.auth.oauth.redirect_sign_out_uri)) {
        const match = finalOutputs.auth.oauth.redirect_sign_out_uri.find(
          (uri: string) => uri.startsWith(currentOrigin)
        );
        if (match) {
          finalOutputs.auth.oauth.redirect_sign_out_uri = [match];
        }
      }
    }

    Amplify.configure(finalOutputs);
    configured = true;
  } catch (e) {
    console.error("Failed to configure Amplify:", e);
  }
}

/** Reset for testing */
export function _resetConfig() {
  configured = false;
}
